language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
env:
 - DJANGO_VERSION_MIN=1.8 DJANGO_VERSION_MAX=1.9
 - DJANGO_VERSION_MIN=1.9 DJANGO_VERSION_MAX=1.10
 - DJANGO_VERSION_MIN=1.10 DJANGO_VERSION_MAX=1.11
install:
 - pip install "django>=$DJANGO_VERSION_MIN,<$DJANGO_VERSION_MAX"
 - "pip install -e ."
 - "pip install coverage coveralls"
script:
 - "coverage run `which django-admin.py` test django_prbac --settings django_prbac.mock_settings --traceback"
after_success:
 - coverage report
 - coveralls

